# This is The Mini Project given by Steel Data and Matthew Steel. 
-- -------------------------------------------------------------------------------------------------------------------------------------------
-- 1. What are the details of all cars purchased in the year 2022?
select c.make,c.type,c.style,c.cost_$,s.purchase_Date
from cars c
join sales s 
		on c.car_id = s.car_id 
where year(purchase_date) = 2022
order by purchase_date;
-- -------------------------------------------------------------------------------------------------------------------------------------------
-- 2. What is the total number of cars sold by each salesperson?
select name,count(*)as total_cars_sold
from sales s
join salespersons sp 
		on s.salesman_id = sp.salesman_id
group by name
order by total_cars_sold desc;
-- -------------------------------------------------------------------------------------------------------------------------------------------
-- 3. What is the total revenue generated by each salesperson?
select sp.name,sum(c.cost_$)as total_revenue
from sales s
join salespersons sp 
		on s.salesman_id = sp.salesman_id
join cars c
		on c.car_id = s.car_id
group by name
order by total_revenue desc;
-- -------------------------------------------------------------------------------------------------------------------------------------------
-- 4. What are the details of the cars sold by each salesperson?
select sp.name,c.*
from sales s
join salespersons sp 
		on s.salesman_id = sp.salesman_id
join cars c
		on c.car_id = s.car_id;
-- -------------------------------------------------------------------------------------------------------------------------------------------
-- 5. What is the total revenue generated by each car type?
select c.type,sum(c.cost_$)as total_revenue
from sales s
join cars c
		on c.car_id = s.car_id
group by c.type
order by total_revenue desc;
-- -------------------------------------------------------------------------------------------------------------------------------------------
-- 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
select sp.name,c.*,s.purchase_date
from sales s
join salespersons sp 
		on s.salesman_id = sp.salesman_id
join cars c
		on c.car_id = s.car_id
where year(purchase_date) = 2021  and sp.name = 'Emily Wong';
-- -------------------------------------------------------------------------------------------------------------------------------------------
-- 7. What is the total revenue generated by the sales of hatchback cars?
select c.style,sum(c.cost_$)as total_sales_rev
from sales s
join cars c
		on c.car_id = s.car_id
where style = 'hatchback'
group by style;
-- -------------------------------------------------------------------------------------------------------------------------------------------
-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
select c.style as car_style,sum(c.cost_$)as total_rev
from sales s
join cars c
		on c.car_id = s.car_id
where c.style ='SUV' and year(s.purchase_date)=2022
group by car_style;
-- ---------------------------------------------------------------------------------------------------------------------------------
-- 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
select sp.name as sales_person_name,sp.city as city,count(s.sale_id)as no_of_cars
from sales s
join salespersons sp 
		on s.salesman_id = sp.salesman_id
join cars c
		on c.car_id = s.car_id 
where year(purchase_date)=2023 
group by sales_person_name,city
order by no_of_cars desc
limit 1;
-- -------------------------------------------------------------------------------------------------------------------------------------------
-- 10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?
select sp.name as sales_person_name,sp.city as city,sp.age as age,sum(c.cost_$)as revenue
from sales s
join salespersons sp 
		on s.salesman_id = sp.salesman_id
join cars c
		on c.car_id = s.car_id 
where year(s.purchase_date) = 2022
group by sales_person_name,city,age
order by revenue desc
limit 1;